### ISSUE TITLE
KeyError: 'bid'

### ISSUE THREAD

**Issue by MomboteQ** [ln-markets/trading-bot#6]
```
INFO:root:Connection to LN Markets ok!
{'RECOMMENDATION': 'BUY', 'BUY': 13, 'SELL': 4, 'NEUTRAL': 9}
{'RECOMMENDATION': 'STRONG_SELL', 'BUY': 1, 'SELL': 16, 'NEUTRAL': 9}
Traceback (most recent call last):
  File "/Users/momboteq/Downloads/trading-bot/main.py", line 7, in <module>
    bot = launcher.bot()
  File "/Users/momboteq/Downloads/trading-bot/launcher.py", line 20, in bot
    return TAS.ta_summary(TAS(lnm_options), 
  File "/Users/momboteq/Downloads/trading-bot/strategies/ta_summary.py", line 141, in ta_summary
    bid = json.loads(self.lnm.get_bid_offer())['bid']
KeyError: 'bid'
```

**Comment by romainlnm** [comment]
Hey, thanks, i need to review the whole code to put it in line with LNM API v2!
Will make it soon

**Comment by romainlnm** [comment]
Should be fixed now with the updates of lnm_client.py and ta_summary.py
